// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.6
// source: proto/heimdall.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*WriteRequest_Metadata
	//	*WriteRequest_ChunkData
	Request       isWriteRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_heimdall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{0}
}

func (x *WriteRequest) GetRequest() isWriteRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *WriteRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Request.(*WriteRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *WriteRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Request.(*WriteRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isWriteRequest_Request interface {
	isWriteRequest_Request()
}

type WriteRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type WriteRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*WriteRequest_Metadata) isWriteRequest_Request() {}

func (*WriteRequest_ChunkData) isWriteRequest_Request() {}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_proto_heimdall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{1}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_heimdall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *WriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_heimdall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReadRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_heimdall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_heimdall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{5}
}

type VersionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamps    []int64                `protobuf:"varint,1,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionList) Reset() {
	*x = VersionList{}
	mi := &file_proto_heimdall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionList) ProtoMessage() {}

func (x *VersionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionList.ProtoReflect.Descriptor instead.
func (*VersionList) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{6}
}

func (x *VersionList) GetTimestamps() []int64 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Files         map[string]*VersionList `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_heimdall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heimdall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_heimdall_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetFiles() map[string]*VersionList {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_heimdall_proto protoreflect.FileDescriptor

const file_proto_heimdall_proto_rawDesc = "" +
	"\n" +
	"\x14proto/heimdall.proto\x12\bheimdall\"p\n" +
	"\fWriteRequest\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.heimdall.FileMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\arequest\"+\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"a\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\vReadRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"-\n" +
	"\fReadResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\"\x0e\n" +
	"\fEmptyRequest\"-\n" +
	"\vVersionList\x12\x1e\n" +
	"\n" +
	"timestamps\x18\x01 \x03(\x03R\n" +
	"timestamps\"\x98\x01\n" +
	"\fListResponse\x127\n" +
	"\x05files\x18\x01 \x03(\v2!.heimdall.ListResponse.FilesEntryR\x05files\x1aO\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.heimdall.VersionListR\x05value:\x028\x012\xcb\x01\n" +
	"\vDataService\x12@\n" +
	"\vWriteAction\x12\x16.heimdall.WriteRequest\x1a\x17.heimdall.WriteResponse(\x01\x12=\n" +
	"\n" +
	"ReadAction\x12\x15.heimdall.ReadRequest\x1a\x16.heimdall.ReadResponse0\x01\x12;\n" +
	"\tListFiles\x12\x16.heimdall.EmptyRequest\x1a\x16.heimdall.ListResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_heimdall_proto_rawDescOnce sync.Once
	file_proto_heimdall_proto_rawDescData []byte
)

func file_proto_heimdall_proto_rawDescGZIP() []byte {
	file_proto_heimdall_proto_rawDescOnce.Do(func() {
		file_proto_heimdall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heimdall_proto_rawDesc), len(file_proto_heimdall_proto_rawDesc)))
	})
	return file_proto_heimdall_proto_rawDescData
}

var file_proto_heimdall_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_heimdall_proto_goTypes = []any{
	(*WriteRequest)(nil),  // 0: heimdall.WriteRequest
	(*FileMetadata)(nil),  // 1: heimdall.FileMetadata
	(*WriteResponse)(nil), // 2: heimdall.WriteResponse
	(*ReadRequest)(nil),   // 3: heimdall.ReadRequest
	(*ReadResponse)(nil),  // 4: heimdall.ReadResponse
	(*EmptyRequest)(nil),  // 5: heimdall.EmptyRequest
	(*VersionList)(nil),   // 6: heimdall.VersionList
	(*ListResponse)(nil),  // 7: heimdall.ListResponse
	nil,                   // 8: heimdall.ListResponse.FilesEntry
}
var file_proto_heimdall_proto_depIdxs = []int32{
	1, // 0: heimdall.WriteRequest.metadata:type_name -> heimdall.FileMetadata
	8, // 1: heimdall.ListResponse.files:type_name -> heimdall.ListResponse.FilesEntry
	6, // 2: heimdall.ListResponse.FilesEntry.value:type_name -> heimdall.VersionList
	0, // 3: heimdall.DataService.WriteAction:input_type -> heimdall.WriteRequest
	3, // 4: heimdall.DataService.ReadAction:input_type -> heimdall.ReadRequest
	5, // 5: heimdall.DataService.ListFiles:input_type -> heimdall.EmptyRequest
	2, // 6: heimdall.DataService.WriteAction:output_type -> heimdall.WriteResponse
	4, // 7: heimdall.DataService.ReadAction:output_type -> heimdall.ReadResponse
	7, // 8: heimdall.DataService.ListFiles:output_type -> heimdall.ListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_heimdall_proto_init() }
func file_proto_heimdall_proto_init() {
	if File_proto_heimdall_proto != nil {
		return
	}
	file_proto_heimdall_proto_msgTypes[0].OneofWrappers = []any{
		(*WriteRequest_Metadata)(nil),
		(*WriteRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heimdall_proto_rawDesc), len(file_proto_heimdall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heimdall_proto_goTypes,
		DependencyIndexes: file_proto_heimdall_proto_depIdxs,
		MessageInfos:      file_proto_heimdall_proto_msgTypes,
	}.Build()
	File_proto_heimdall_proto = out.File
	file_proto_heimdall_proto_goTypes = nil
	file_proto_heimdall_proto_depIdxs = nil
}
